### ISSUE TITLE
pacman packages for the autovala plugins

### ISSUE THREAD

**Issue by bb010g** [rastersoft/autovala#49]
Probably easiest to do with multiple `PKGBUILD`s.

**Comment by rastersoft** [comment]
In fact, this last version has preliminary support for creating PKGBUILD files. The problem is that I'm naive about Pacman, and currently those files only allow to create a package from the locally downloaded source, but they aren't a fully-fledged PKGBUILD files that download the source from the internet. At this moment I'm quite busy with my work-that-pays-the-bills, but this weekend I hope to be able to give to this some love, and then create PKGBUILD files for everything.

**Comment by rastersoft** [comment]
Ok, done. Now I added generic PKGBUILD files both for autovala and the gedit plugin, but also will try to upload specific versions to AUR, that download the source from GitHub.

**Comment by rastersoft** [comment]
Ok, reopening. I found a problem: if I create a package for autovala, it creates a folder "/usr/lib64" and puts inside all the libraries; the problem is that in the system, that is a link to "/usr/lib", so when I try to install the package with pacman, it says that "/usr/lib64" already exists... Do you know how to fix this?

**Comment by bb010g** [comment]
https://bbs.archlinux.org/viewtopic.php?id=192090

**Comment by rastersoft** [comment]
Ok, fixed. Thanks for the tips!

BTW... Do you know how to configure PKGBUILD files for python3 programs? Is there a python package that allows to use distutils to generate it, like already are for RPM and DEB files?

**Comment by bb010g** [comment]
I haven't dealt much with Python3 PKGBUILDs. I would recommend asking around the Arch BBS or #archlinux on Freenode; everyone's pretty helpful there.

**Comment by bb010g** [comment]
[**@rastersoft**](https://github.com/rastersoft) commented on [May 10, 2015, 2:42 PM PDT](https://github.com/rastersoft/autovala/issues/49#issuecomment-100704461 "2015-05-10T21:42:26Z - Replied by Github Comment Enhancer"):
> Now I added generic PKGBUILD files both for autovala and the gedit plugin, but also will try to upload specific versions to AUR, that download the source from GitHub.

Any update on the AUR packages?

**Comment by rastersoft** [comment]
I will try to upload them.

**Comment by bb010g** [comment]
Could we get them on AUR4?

**Comment by rastersoft** [comment]
Don't know. I use Multipackager to create packages for Pacman and upload them to my home page, but don't know how to upload them to AUR (I use Debian, so some details are quite obscure for me).

If you can help me...

**Comment by rastersoft** [comment]
The packages are available at http://www.rastersoft.com/programas/autovala.html and http://www.rastersoft.com/programas/autovala_gedit.html

**Comment by rastersoft** [comment]
Please, check the new packages.
