### ISSUE TITLE
Vala 0.30 required?

### ISSUE THREAD

**Issue by ztefn** [rastersoft/autovala#71]
Latest autovala (version 0.99.41) jumps vala dependency from 0.20 to 0.30, is that necessary? The build environment I use for my own vala application is based on vala 0.26 and therefore I cannot compile the latest version of autovala anymore.

**Comment by rastersoft** [comment]
I decided to jump it to the version used by me just to be sure that there aren't problems due to using some characteristic not available in old versions, but you should be able to change the minimum version by editing all the CMakeList.txt files inside /src. If it compiles, it should work fine.

BTW: which distro are you using? Ubuntu 16.04 has version 0.30...

**Comment by ztefn** [comment]
Thanks, changing the version in all (three) CMakeList.txt files makes it compile again!

I had setup my build environment inside a virtual machine back when I started the Vala port of Haguichi in late 2014. It's a Frankenstein environment based on Ubuntu GNOME 14.10 and GNOME3 Staging PPA to provide GTK+ 3.14 which I then needed instead of the 3.12 it came with...

I could setup a new build environment based on Ubuntu 16.04, but hey, if it ain't broken... :)
And it prevents me from depending on newer stuff that's not available in slow moving targets like Debian (version 8 ships with GTK 3.14+ and Vala 0.26 too).
