### ISSUE TITLE
Doesn't accept genie (*.gs) files

### ISSUE THREAD

**Issue by darkoverlordofdata** [rastersoft/autovala#75]
Autovala doesn't find genie files. 

Even worse, after I add them all manually to my .avprj, they are removed the next time I run autovala refresh.

**Comment by rastersoft** [comment]
Hi:

I suspect that you forgot to remove the asterisk before the "vala_source" line.

Anyway, I just uploaded to the repo a preliminary version to autovala with full support for genie. Please, test it and comment me what problems and bugs do you find.

To initialize a genie project just use "autovala ginit PROJECT_NAME" instead of "init".

In theory it should be able to detect the "uses PACKAGE_NAME", just like in vala.

The only doubt I have is how to extract the translatable strings... Which command do you use?

**Comment by darkoverlordofdata** [comment]
Yes, this works well. Thanks!
